"""Built-in module: custom fonts injection.

Copies font files (TrueType, OpenType, TrueType collections, etc.) into the
offline Windows image so they are available to all users immediately after
installation.

The module places fonts in:
  ``$OEM$\\$$\\Fonts``

and registers them under:
  ``HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Fonts``

via a ``$OEM$\\$$\\Setup\\Scripts\\Register-Fonts.ps1`` script.

Reference:
  https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/
  add-and-remove-fonts-offline
"""

from __future__ import annotations

import shutil
from pathlib import Path

from win11_customizer.modules import BaseModule, ModuleMetadata

# Font file extensions recognised by Windows
FONT_EXTENSIONS = {".ttf", ".otf", ".ttc", ".fon", ".otc"}

_PS_REGISTER = """\
# Register-Fonts.ps1 – generated by win11-customizer
# Register fonts placed in $env:SystemRoot\\Fonts by win11-customizer
$fontsDir = "$env:SystemRoot\\Fonts"
$regPath  = "HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Fonts"
Get-ChildItem -Path $fontsDir -Include *.ttf,*.otf,*.ttc,*.fon,*.otc -Recurse | ForEach-Object {
    $name = $_.BaseName
    $file = $_.Name
    if (-not (Get-ItemProperty -Path $regPath -Name $name -ErrorAction SilentlyContinue)) {
        New-ItemProperty -Path $regPath -Name $name -Value $file -PropertyType String -Force | Out-Null
        Write-Host "Registered font: $name ($file)"
    }
}
"""


class FontsModule(BaseModule):
    """Inject custom font files into the offline Windows image.

    Configuration keys
    ------------------
    ``fonts`` (list[str])
        List of paths to individual font files *or* directories that will
        be scanned for font files.  Directories are searched non-recursively
        by default.
    ``recurse`` (bool, default ``False``)
        Recursively scan directories for font files.
    """

    metadata = ModuleMetadata(
        name="fonts",
        description="Inject custom font files (TTF, OTF, TTC …) into the Windows image",
        category="ui",
    )

    def apply(self, work_dir: Path) -> None:
        font_sources: list[str] = self.config.get("fonts", [])
        if not font_sources:
            self._logger.warning("FontsModule: no font paths specified.")
            return

        recurse: bool = bool(self.config.get("recurse", False))

        # Collect all font files
        font_files: list[Path] = []
        for src_str in font_sources:
            src = Path(src_str).resolve()
            if src.is_file() and src.suffix.lower() in FONT_EXTENSIONS:
                font_files.append(src)
            elif src.is_dir():
                pattern = "**/*" if recurse else "*"
                for f in src.glob(pattern):
                    if f.is_file() and f.suffix.lower() in FONT_EXTENSIONS:
                        font_files.append(f)
            else:
                self._logger.warning("Font path not found or unrecognised extension: %s", src)

        if not font_files:
            self._logger.warning("FontsModule: no font files found.")
            return

        # Destination: $OEM$\$$\Fonts  ($$  maps to  C:\Windows)
        fonts_dest = work_dir / "$OEM$" / "$$" / "Fonts"
        fonts_dest.mkdir(parents=True, exist_ok=True)

        for font in font_files:
            dest = fonts_dest / font.name
            shutil.copy2(font, dest)
            self._logger.info("Copied font: %s → %s", font, dest)

        # Write registration script
        scripts_dir = work_dir / "$OEM$" / "$$" / "Setup" / "Scripts"
        scripts_dir.mkdir(parents=True, exist_ok=True)
        ps_path = scripts_dir / "Register-Fonts.ps1"
        ps_path.write_text(_PS_REGISTER, encoding="utf-8")

        cmd_path = scripts_dir / "SetupComplete.cmd"
        existing = cmd_path.read_text(encoding="utf-8") if cmd_path.exists() else "@echo off\r\n"
        if "Register-Fonts.ps1" not in existing:
            existing = existing.rstrip("\r\n")
            existing += '\r\nPowerShell -NonInteractive -ExecutionPolicy Bypass -File "%~dp0Register-Fonts.ps1"\r\n'
            cmd_path.write_text(existing, encoding="utf-8")

        self._logger.info("Injected %d font file(s).", len(font_files))
