"""Built-in module: Microsoft Office / Microsoft 365 silent deployment.

Embeds an Office Deployment Tool (ODT) ``Configuration.xml`` into the ISO and
injects a ``$OEM$\\$$\\Setup\\Scripts`` script that triggers a silent Office
install on first boot.  The user must supply (or reference) their own Office
deployment source or let the installer download from CDN.

Alternatively this module can embed a pre-downloaded Office source tree into
``$OEM$\\$$\\Apps\\Office`` so the installation is entirely offline.

Reference:
  https://learn.microsoft.com/en-us/deployoffice/office-deployment-tool-
  configuration-options
"""

from __future__ import annotations

import shutil
import textwrap
from pathlib import Path
from typing import Any

from win11_customizer.modules import BaseModule, ModuleMetadata

# ---------------------------------------------------------------------------
# ODT Configuration.xml template
# ---------------------------------------------------------------------------

_ODT_TEMPLATE = textwrap.dedent("""\
    <Configuration>
      <Add OfficeClientEdition="{arch}" Channel="{channel}">
        <Product ID="{product_id}">
          <Language ID="{language}" />
          {exclude_apps}
        </Product>
      </Add>
      <Property Name="FORCEAPPSHUTDOWN" Value="TRUE" />
      <Property Name="SharedComputerLicensing" Value="{shared_licensing}" />
      <Display Level="None" AcceptEULA="TRUE" />
      <Logging Level="Standard" Path="%temp%\\ODT" />
      {source_path_line}
    </Configuration>
""")

_EXCLUDE_TEMPLATE = '<ExcludeApp ID="{app_id}" />'

_SETUP_PS = textwrap.dedent("""\
    # Install-Office.ps1 – generated by win11-customizer
    $setup = Join-Path $PSScriptRoot 'setup.exe'
    $config = Join-Path $PSScriptRoot 'Office-Configuration.xml'
    if (-not (Test-Path $setup)) {{
        Write-Host 'setup.exe not found. Downloading ODT...'
        $odtUrl = 'https://download.microsoft.com/download/2/7/A/27AF1BE6-DD20-4CB4-B154-EBAB8A7D4A7E/officedeploymenttool_17928-20156.exe'
        Invoke-WebRequest -Uri $odtUrl -OutFile "$env:TEMP\\odt.exe" -UseBasicParsing
        Start-Process -FilePath "$env:TEMP\\odt.exe" -ArgumentList "/quiet /extract:$PSScriptRoot" -Wait
        $setup = Join-Path $PSScriptRoot 'setup.exe'
    }}
    Write-Host 'Starting Office installation...'
    Start-Process -FilePath $setup -ArgumentList "/configure `"$config`"" -Wait -NoNewWindow
    Write-Host 'Office installation complete.'
""")


class OfficeModule(BaseModule):
    """Embed an ODT config and (optionally) trigger a silent Office install.

    Configuration keys
    ------------------
    ``product_id`` (str, default ``"O365ProPlusRetail"``)
        ODT product ID, e.g. ``"O365ProPlusRetail"``,
        ``"ProPlus2021Volume"``, ``"HomeStudent2021Retail"``.
    ``arch`` (str, default ``"64"``)
        ``"64"`` or ``"32"``.
    ``channel`` (str, default ``"Current"``)
        Update channel: ``"Current"``, ``"Monthly"``, ``"SemiAnnual"``,
        ``"BetaChannel"``, etc.
    ``language`` (str, default ``"MatchOS"``)
        Language ID, e.g. ``"en-us"`` or ``"MatchOS"``.
    ``exclude_apps`` (list[str], default ``[]``)
        App IDs to exclude, e.g. ``["Access", "Publisher", "Groove"]``.
    ``shared_licensing`` (bool, default ``False``)
        Enable shared computer licensing (RDS / VDI scenarios).
    ``source_path`` (str, optional)
        Local path to a pre-downloaded Office source tree.  When provided,
        the source tree is copied into the ISO.
    ``odt_setup_exe`` (str, optional)
        Path to ``setup.exe`` from the ODT.  Bundled into the ISO when given.
    """

    metadata = ModuleMetadata(
        name="office",
        description="Embed an ODT Configuration.xml for silent Microsoft Office / M365 installation",
        category="applications",
    )

    def apply(self, work_dir: Path) -> None:
        product_id: str = self.config.get("product_id", "O365ProPlusRetail")
        arch: str = str(self.config.get("arch", "64"))
        channel: str = self.config.get("channel", "Current")
        language: str = self.config.get("language", "MatchOS")
        exclude_apps: list[str] = self.config.get("exclude_apps", [])
        shared_licensing: bool = bool(self.config.get("shared_licensing", False))
        source_path: str | None = self.config.get("source_path")
        odt_setup_exe: str | None = self.config.get("odt_setup_exe")

        scripts_dir = work_dir / "$OEM$" / "$$" / "Setup" / "Scripts"
        scripts_dir.mkdir(parents=True, exist_ok=True)

        # Build exclude XML lines
        exclude_xml = "\n          ".join(
            _EXCLUDE_TEMPLATE.format(app_id=a) for a in exclude_apps
        )

        source_path_line = ""
        if source_path:
            local_src = Path(source_path).resolve()
            if not local_src.exists():
                raise FileNotFoundError(f"Office source path not found: {local_src}")
            iso_apps_dir = work_dir / "$OEM$" / "$$" / "Apps" / "Office"
            shutil.copytree(str(local_src), str(iso_apps_dir), dirs_exist_ok=True)
            source_path_line = '<SourcePath Value="%SystemRoot%\\Apps\\Office" />'
            self._logger.info("Copied Office source tree: %s → %s", local_src, iso_apps_dir)

        xml_content = _ODT_TEMPLATE.format(
            arch=arch,
            channel=channel,
            product_id=product_id,
            language=language,
            exclude_apps=exclude_xml,
            shared_licensing="1" if shared_licensing else "0",
            source_path_line=source_path_line,
        )
        config_path = scripts_dir / "Office-Configuration.xml"
        config_path.write_text(xml_content, encoding="utf-8")
        self._logger.info("Written Office ODT configuration: %s", config_path)

        if odt_setup_exe:
            odt_src = Path(odt_setup_exe).resolve()
            if not odt_src.is_file():
                raise FileNotFoundError(f"ODT setup.exe not found: {odt_src}")
            shutil.copy2(odt_src, scripts_dir / "setup.exe")
            self._logger.info("Copied ODT setup.exe: %s", odt_src)

        # Write the install script
        ps_path = scripts_dir / "Install-Office.ps1"
        ps_path.write_text(_SETUP_PS, encoding="utf-8")

        cmd_path = scripts_dir / "SetupComplete.cmd"
        existing = cmd_path.read_text(encoding="utf-8") if cmd_path.exists() else "@echo off\r\n"
        if "Install-Office.ps1" not in existing:
            existing = existing.rstrip("\r\n")
            existing += '\r\nPowerShell -NonInteractive -ExecutionPolicy Bypass -File "%~dp0Install-Office.ps1"\r\n'
            cmd_path.write_text(existing, encoding="utf-8")
