"""Built-in module: OneDrive configuration / removal.

OneDrive is deeply integrated into Windows 11 but many users and enterprise
deployments prefer to remove or disable it.  This module:

* Writes a ``$OEM$\\$$\\Setup\\Scripts`` PowerShell script that uninstalls
  OneDrive on first boot.
* Optionally writes registry entries that prevent OneDrive from auto-starting
  or advertising itself.
* Optionally removes the OneDrive setup binary from the extracted ISO tree
  (``Windows\\SysWOW64\\OneDriveSetup.exe`` and
  ``Windows\\System32\\OneDriveSetup.exe``).

Reference:
  https://learn.microsoft.com/en-us/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services#bkmk-onedrive
"""

from __future__ import annotations

import textwrap
from pathlib import Path

from win11_customizer.modules import BaseModule, ModuleMetadata

_UNINSTALL_SCRIPT = textwrap.dedent("""\
    # Remove-OneDrive.ps1 – generated by win11-customizer
    # Kill any running OneDrive processes
    Stop-Process -Name OneDrive -Force -ErrorAction SilentlyContinue

    # Locate and run the uninstaller
    $setup = @(
        "$env:SystemRoot\\SysWOW64\\OneDriveSetup.exe",
        "$env:SystemRoot\\System32\\OneDriveSetup.exe",
        "$env:localappdata\\Microsoft\\OneDrive\\OneDriveSetup.exe"
    ) | Where-Object { Test-Path $_ } | Select-Object -First 1

    if ($setup) {
        & $setup /uninstall /quiet
    }

    # Remove leftover shell namespace registrations
    $clsids = @(
        'HKCR:\\CLSID\\{018D5C66-4533-4307-9B53-224DE2ED1FE6}',
        'HKCR:\\Wow6432Node\\CLSID\\{018D5C66-4533-4307-9B53-224DE2ED1FE6}'
    )
    foreach ($clsid in $clsids) {
        if (Test-Path $clsid) {
            Set-ItemProperty -Path $clsid -Name System.IsPinnedToNameSpaceTree -Value 0 -ErrorAction SilentlyContinue
        }
    }

    # Prevent OneDrive from running at startup
    reg delete "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run" /v OneDrive /f 2>$null
""")

_DISABLE_REG = textwrap.dedent("""\
    Windows Registry Editor Version 5.00

    ; Disable OneDrive integration via group policy
    [HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\OneDrive]
    "DisableFileSyncNGSC"=dword:00000001
    "DisableFileSync"=dword:00000001
    "DisableLibrariesDefaultSaveToOneDrive"=dword:00000001

    ; Remove OneDrive from the navigation pane (current user default)
    [HKEY_LOCAL_MACHINE\\SOFTWARE\\Classes\\CLSID\\{018D5C66-4533-4307-9B53-224DE2ED1FE6}]
    "System.IsPinnedToNameSpaceTree"=dword:00000000

    [HKEY_LOCAL_MACHINE\\SOFTWARE\\Classes\\WOW6432Node\\CLSID\\{018D5C66-4533-4307-9B53-224DE2ED1FE6}]
    "System.IsPinnedToNameSpaceTree"=dword:00000000
""")


class OneDriveModule(BaseModule):
    """Disable or remove Microsoft OneDrive.

    Configuration keys
    ------------------
    ``action`` (str)
        * ``"disable"`` *(default)* – inject registry keys that disable
          OneDrive via group policy; OneDrive remains installed.
        * ``"remove"`` – inject a PowerShell uninstall script *and* the
          disable registry keys; runs at first boot.
        * ``"remove_setup_binary"`` – additionally delete
          ``OneDriveSetup.exe`` from the offline ISO tree if present
          (requires the ISO to have been extracted first and the relevant
          file to exist).
    """

    metadata = ModuleMetadata(
        name="onedrive",
        description="Disable or remove Microsoft OneDrive from the Windows 11 image",
        category="cleanup",
    )

    def apply(self, work_dir: Path) -> None:
        action: str = self.config.get("action", "disable")

        scripts_dir = work_dir / "$OEM$" / "$$" / "Setup" / "Scripts"
        reg_dir = work_dir / "$OEM$" / "$$" / "Setup" / "Scripts"

        scripts_dir.mkdir(parents=True, exist_ok=True)

        # Always write the disable registry file
        reg_file = reg_dir / "disable_onedrive.reg"
        reg_file.write_text(_DISABLE_REG, encoding="utf-16")
        self._logger.info("Written OneDrive disable registry file: %s", reg_file)

        if action in ("remove", "remove_setup_binary"):
            ps_path = scripts_dir / "Remove-OneDrive.ps1"
            ps_path.write_text(_UNINSTALL_SCRIPT, encoding="utf-8")
            self._logger.info("Written OneDrive removal script: %s", ps_path)
            self._wire_setup_cmd(scripts_dir, "Remove-OneDrive.ps1")

        if action == "remove_setup_binary":
            for rel in (
                "Windows/SysWOW64/OneDriveSetup.exe",
                "Windows/System32/OneDriveSetup.exe",
            ):
                target = work_dir / rel
                if target.exists():
                    target.unlink()
                    self._logger.info("Removed setup binary: %s", target)

        # Wire registry import into SetupComplete.cmd
        self._wire_setup_cmd(scripts_dir, "disable_onedrive.reg", is_reg=True)

    # ------------------------------------------------------------------

    @staticmethod
    def _wire_setup_cmd(scripts_dir: Path, filename: str, *, is_reg: bool = False) -> None:
        cmd_path = scripts_dir / "SetupComplete.cmd"
        existing = cmd_path.read_text(encoding="utf-8") if cmd_path.exists() else "@echo off\r\n"
        if filename not in existing:
            existing = existing.rstrip("\r\n")
            if is_reg:
                existing += f'\r\nreg import "%~dp0{filename}" /reg:64\r\n'
            else:
                existing += f'\r\nPowerShell -NonInteractive -ExecutionPolicy Bypass -File "%~dp0{filename}"\r\n'
            cmd_path.write_text(existing, encoding="utf-8")
