"""Built-in module: power plan configuration.

Sets the active Windows power plan in the offline image via a
``$OEM$\\$$\\Setup\\Scripts\\Configure-PowerPlan.ps1`` script that is
automatically executed at first boot.

On Windows hosts with DISM access the module can alternatively inject the
selected plan into the offline image by modifying the registry hive.

Reference:
  https://learn.microsoft.com/en-us/windows-hardware/customize/power-settings/
  configure-power-settings
"""

from __future__ import annotations

import textwrap
from pathlib import Path

from win11_customizer.modules import BaseModule, ModuleMetadata

# GUIDs for the built-in Windows power plans
KNOWN_PLANS: dict[str, str] = {
    "balanced":         "381b4222-f694-41f0-9685-ff5bb260df2e",
    "high_performance": "8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c",
    "power_saver":      "a1841308-3541-4fab-bc81-f71556f20b4a",
    # Windows 11 / modern standby
    "ultimate_performance": "e9a42b02-d5df-448d-aa00-03f14749eb61",
}

_PS_TEMPLATE = textwrap.dedent("""\
    # Configure-PowerPlan.ps1 – generated by win11-customizer
    # Activate power plan: {plan_name}
    $guid = '{plan_guid}'
    $existing = powercfg /list | Select-String $guid
    if (-not $existing) {{
        # Import the plan from the default list (Ultimate Performance may need to be provisioned)
        powercfg /duplicatescheme $guid | Out-Null
    }}
    powercfg /setactive $guid
    Write-Host "Power plan set to: {plan_name} ($guid)"
""")


class PowerModule(BaseModule):
    """Select the active power plan via a first-boot PowerShell script.

    Configuration keys
    ------------------
    ``plan`` (str, default ``"balanced"``)
        Power plan to activate.  Built-in names:
        ``"balanced"``, ``"high_performance"``, ``"power_saver"``,
        ``"ultimate_performance"``.
    ``custom_guid`` (str, optional)
        Use a custom power-plan GUID instead of a named plan.
    """

    metadata = ModuleMetadata(
        name="power",
        description="Select Windows power plan (balanced, high_performance, power_saver, ultimate_performance)",
        category="performance",
    )

    def apply(self, work_dir: Path) -> None:
        plan: str = self.config.get("plan", "balanced").lower()
        custom_guid: str | None = self.config.get("custom_guid")

        if custom_guid:
            plan_guid = custom_guid
            plan_name = f"custom ({custom_guid})"
        else:
            plan_guid = KNOWN_PLANS.get(plan)
            if plan_guid is None:
                available = ", ".join(sorted(KNOWN_PLANS))
                raise ValueError(
                    f"Unknown power plan '{plan}'.  Available: {available}"
                )
            plan_name = plan

        scripts_dir = work_dir / "$OEM$" / "$$" / "Setup" / "Scripts"
        scripts_dir.mkdir(parents=True, exist_ok=True)

        ps_path = scripts_dir / "Configure-PowerPlan.ps1"
        ps_path.write_text(
            _PS_TEMPLATE.format(plan_name=plan_name, plan_guid=plan_guid),
            encoding="utf-8",
        )
        self._logger.info("Written power plan script: %s  (plan=%s)", ps_path, plan_name)

        cmd_path = scripts_dir / "SetupComplete.cmd"
        existing = cmd_path.read_text(encoding="utf-8") if cmd_path.exists() else "@echo off\r\n"
        if "Configure-PowerPlan.ps1" not in existing:
            existing = existing.rstrip("\r\n")
            existing += '\r\nPowerShell -NonInteractive -ExecutionPolicy Bypass -File "%~dp0Configure-PowerPlan.ps1"\r\n'
            cmd_path.write_text(existing, encoding="utf-8")
