"""Built-in module: Windows Subsystem for Linux (WSL) enablement.

This module enables WSL and (optionally) WSL2 in the offline image via DISM
optional features, and injects a first-boot PowerShell script that installs a
chosen Linux distribution through the Windows Store / ``wsl --install``.

WSL 2 requires:
* ``VirtualMachinePlatform`` optional feature.
* The WSL2 kernel update package (downloaded at runtime by ``wsl --update``).
* Hardware-level virtualisation support (Intel VT-x / AMD-V).

Reference:
  https://learn.microsoft.com/en-us/windows/wsl/install
  https://learn.microsoft.com/en-us/windows/wsl/enterprise
"""

from __future__ import annotations

import textwrap
from pathlib import Path

from win11_customizer.modules import BaseModule, ModuleMetadata

# Distributions supported by ``wsl --install --distribution <name>``
KNOWN_DISTROS: list[str] = [
    "Ubuntu",
    "Ubuntu-22.04",
    "Ubuntu-20.04",
    "Ubuntu-18.04",
    "Debian",
    "kali-linux",
    "SLES-15",
    "openSUSE-Leap-15.5",
    "openSUSE-Tumbleweed",
    "OracleLinux_8_7",
    "OracleLinux_9_1",
    "AlmaLinux-9",
    "AlmaLinux-8",
    "FedoraLinux-42",
    "Arch",
]

_PS_TEMPLATE = textwrap.dedent("""\
    # Enable-WSL.ps1 – generated by win11-customizer
    # Enable required Windows features
    Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux -NoRestart -All
    Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform -NoRestart -All

    # Update WSL kernel and set default version to 2
    wsl --update
    wsl --set-default-version 2

    {distro_install}
""")

_DISTRO_INSTALL = "wsl --install --distribution {distro} --no-launch"
_NO_DISTRO = "Write-Host 'WSL enabled. Install a distribution with: wsl --install'"


class WSLModule(BaseModule):
    """Enable Windows Subsystem for Linux (WSL) in the Windows 11 image.

    Configuration keys
    ------------------
    ``version`` (int, default 2)
        WSL version to set as default (``1`` or ``2``).
    ``distro`` (str, optional)
        Linux distribution to install automatically at first boot.
        Leave empty to enable WSL without installing a distro.
        Example values: ``"Ubuntu"``, ``"Debian"``, ``"kali-linux"``.
    ``use_dism`` (bool, default ``True``)
        Also add ``Microsoft-Windows-Subsystem-Linux`` and
        ``VirtualMachinePlatform`` to the features module config
        (requires a Windows host with DISM).  When ``False``, only the
        first-boot PowerShell script is injected.
    """

    metadata = ModuleMetadata(
        name="wsl",
        description="Enable Windows Subsystem for Linux and optionally install a distribution",
        category="features",
    )

    def apply(self, work_dir: Path) -> None:
        distro: str | None = self.config.get("distro")

        if distro and distro not in KNOWN_DISTROS:
            self._logger.warning(
                "Unknown distro '%s' – will attempt install anyway.  "
                "Known distros: %s",
                distro,
                ", ".join(KNOWN_DISTROS),
            )

        distro_line = _DISTRO_INSTALL.format(distro=distro) if distro else _NO_DISTRO
        script = _PS_TEMPLATE.format(distro_install=distro_line)

        scripts_dir = work_dir / "$OEM$" / "$$" / "Setup" / "Scripts"
        scripts_dir.mkdir(parents=True, exist_ok=True)

        ps_path = scripts_dir / "Enable-WSL.ps1"
        ps_path.write_text(script, encoding="utf-8")
        self._logger.info("Written WSL enable script: %s", ps_path)

        cmd_path = scripts_dir / "SetupComplete.cmd"
        existing = cmd_path.read_text(encoding="utf-8") if cmd_path.exists() else "@echo off\r\n"
        if "Enable-WSL.ps1" not in existing:
            existing = existing.rstrip("\r\n")
            existing += '\r\nPowerShell -NonInteractive -ExecutionPolicy Bypass -File "%~dp0Enable-WSL.ps1"\r\n'
            cmd_path.write_text(existing, encoding="utf-8")
